// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240523170517_customernumber_not_required")]
    partial class customernumber_not_required
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BusinessId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_BusinessId");

                    b.ToTable("Business", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            Address = "Snarøyveien 30",
                            County = "Fornebu",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 23, 17, 5, 17, 269, DateTimeKind.Utc).AddTicks(9440),
                            Email = "noreply@telenor.com",
                            IsDeleted = false,
                            Name = "Telenor",
                            PostCode = 1360
                        });
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerNumber"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivateCustomer")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("OrganizationNr")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_CustomerId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("04ae4661-009e-47c3-a96f-e8b8ed15b39a"),
                            Address = "Daniels hus",
                            BusinessId = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            County = "Oslo",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 23, 17, 5, 17, 270, DateTimeKind.Utc).AddTicks(2220),
                            CustomerNumber = 0,
                            Email = "Daniel@gmail.com",
                            IsDeleted = false,
                            IsPrivateCustomer = true,
                            Name = "Daniel Holtet",
                            OrganizationNr = 123456789,
                            PhoneNumber = "12345678",
                            PostCode = 0,
                            StatusId = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c")
                        },
                        new
                        {
                            Id = new Guid("45d471de-7122-4dcd-90f7-2246af8125e1"),
                            Address = "Benjamins hus",
                            BusinessId = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            County = "Tønsberg",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 23, 17, 5, 17, 270, DateTimeKind.Utc).AddTicks(2270),
                            CustomerNumber = 0,
                            Email = "Benjamin@gmail.com",
                            IsDeleted = false,
                            IsPrivateCustomer = false,
                            Name = "Test",
                            OrganizationNr = 135734567,
                            PhoneNumber = "12345578",
                            PostCode = 0,
                            StatusId = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleId");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccafb929-aa82-4981-96f9-53864b688c89"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 23, 17, 5, 17, 270, DateTimeKind.Utc).AddTicks(910),
                            IsDeleted = false,
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("dd5a13da-11e4-4554-a697-76a4102fd72e"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 23, 17, 5, 17, 270, DateTimeKind.Utc).AddTicks(920),
                            IsDeleted = false,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StatusId");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_StatusId");

                    b.ToTable("Status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 23, 17, 5, 17, 270, DateTimeKind.Utc).AddTicks(1180),
                            IsDeleted = false,
                            Name = "Lead"
                        },
                        new
                        {
                            Id = new Guid("08bc99d4-87ac-4f56-89e9-af19ab20ab95"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 23, 17, 5, 17, 270, DateTimeKind.Utc).AddTicks(1180),
                            IsDeleted = false,
                            Name = "Tatt Kontakt"
                        },
                        new
                        {
                            Id = new Guid("2b8cc7ea-d47b-4d01-90d9-1581ce380422"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 23, 17, 5, 17, 270, DateTimeKind.Utc).AddTicks(1180),
                            IsDeleted = false,
                            Name = "I Prosess"
                        },
                        new
                        {
                            Id = new Guid("edd4e8aa-d3bd-40f1-8a97-8da40cef43bb"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 23, 17, 5, 17, 270, DateTimeKind.Utc).AddTicks(1180),
                            IsDeleted = false,
                            Name = "Kunde"
                        },
                        new
                        {
                            Id = new Guid("60e8fa5e-560d-41f7-b16c-593e5b0cfd3b"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 23, 17, 5, 17, 270, DateTimeKind.Utc).AddTicks(1180),
                            IsDeleted = false,
                            Name = "Avslått"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_UserId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.HasOne("Domain.Entities.Business", "Business")
                        .WithMany("Customers")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Status", "Status")
                        .WithMany("Customers")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Business", "Business")
                        .WithMany("Users")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Business", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Status", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
