// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BusinessId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_BusinessId");

                    b.ToTable("Business", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            Address = "Snarøyveien 30",
                            County = "Fornebu",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(7120),
                            Email = "noreply@telenor.com",
                            IsDeleted = false,
                            Name = "Telenor",
                            PostCode = 1360
                        });
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerNumber"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivateCustomer")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("OrganizationNr")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_CustomerId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d5496e4-86c0-400c-b224-cc1c0ae4048c"),
                            Address = "Snarøyveien 30",
                            BusinessId = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            County = "Fornebu",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(9520),
                            CustomerNumber = 0,
                            Email = "contact@telenor.com",
                            IsDeleted = false,
                            IsPrivateCustomer = false,
                            Name = "Telenor",
                            OrganizationNr = 911066905,
                            PhoneNumber = "67800000",
                            PostCode = 1360,
                            StatusId = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c")
                        },
                        new
                        {
                            Id = new Guid("04ab9f8b-6051-458d-8b51-90d6bf6eb5dc"),
                            Address = "Forusbeen 50",
                            BusinessId = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            County = "Stavanger",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(9530),
                            CustomerNumber = 0,
                            Email = "contact@equinor.com",
                            IsDeleted = false,
                            IsPrivateCustomer = false,
                            Name = "Equinor",
                            OrganizationNr = 923609016,
                            PhoneNumber = "51990000",
                            PostCode = 4035,
                            StatusId = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c")
                        },
                        new
                        {
                            Id = new Guid("426a4a81-5a81-4723-8626-b811e2e2d76b"),
                            Address = "Drammensveien 260",
                            BusinessId = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            County = "Oslo",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(9530),
                            CustomerNumber = 0,
                            Email = "contact@hydro.com",
                            IsDeleted = false,
                            IsPrivateCustomer = false,
                            Name = "Norsk Hydro",
                            OrganizationNr = 914778271,
                            PhoneNumber = "22532000",
                            PostCode = 283,
                            StatusId = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c")
                        },
                        new
                        {
                            Id = new Guid("381d800f-f5f7-4dae-923a-8e34ec7e8c68"),
                            Address = "Drammensveien 131",
                            BusinessId = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            County = "Oslo",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(9540),
                            CustomerNumber = 0,
                            Email = "contact@yara.com",
                            IsDeleted = false,
                            IsPrivateCustomer = false,
                            Name = "Yara International",
                            OrganizationNr = 919937882,
                            PhoneNumber = "24155000",
                            PostCode = 277,
                            StatusId = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c")
                        },
                        new
                        {
                            Id = new Guid("da1a7389-23d1-40b2-887b-f76f6aff232b"),
                            Address = "Dronning Eufemias gate 30",
                            BusinessId = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            County = "Oslo",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(9540),
                            CustomerNumber = 0,
                            Email = "contact@dnb.no",
                            IsDeleted = false,
                            IsPrivateCustomer = false,
                            Name = "DNB",
                            OrganizationNr = 984851006,
                            PhoneNumber = "91504800",
                            PostCode = 191,
                            StatusId = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c")
                        },
                        new
                        {
                            Id = new Guid("d23e16e3-3a49-4330-a188-7ae7aca6cae3"),
                            Address = "Skøyen",
                            BusinessId = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            County = "Oslo",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(9550),
                            CustomerNumber = 0,
                            Email = "contact@orkla.no",
                            IsDeleted = false,
                            IsPrivateCustomer = false,
                            Name = "Orkla",
                            OrganizationNr = 910747711,
                            PhoneNumber = "22542000",
                            PostCode = 277,
                            StatusId = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c")
                        },
                        new
                        {
                            Id = new Guid("efb6e5e4-c6f9-4427-9ae5-33204e807874"),
                            Address = "Lakkegata 23",
                            BusinessId = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            County = "Oslo",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(9560),
                            CustomerNumber = 0,
                            Email = "contact@tine.no",
                            IsDeleted = false,
                            IsPrivateCustomer = false,
                            Name = "Tine",
                            OrganizationNr = 874560982,
                            PhoneNumber = "03080",
                            PostCode = 187,
                            StatusId = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c")
                        },
                        new
                        {
                            Id = new Guid("24a15855-30bd-4081-97c2-5217bd1c6779"),
                            Address = "Schweigaards gate 21",
                            BusinessId = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            County = "Oslo",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(9560),
                            CustomerNumber = 0,
                            Email = "contact@gjensidige.no",
                            IsDeleted = false,
                            IsPrivateCustomer = false,
                            Name = "Gjensidige",
                            OrganizationNr = 995568217,
                            PhoneNumber = "91503100",
                            PostCode = 191,
                            StatusId = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c")
                        },
                        new
                        {
                            Id = new Guid("572e6272-3445-4ec8-a9c5-82cf01cbad72"),
                            Address = "Hamar",
                            BusinessId = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            County = "Hedmark",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(9570),
                            CustomerNumber = 0,
                            Email = "contact@norsk-tipping.no",
                            IsDeleted = false,
                            IsPrivateCustomer = false,
                            Name = "Norsk Tipping",
                            OrganizationNr = 982480105,
                            PhoneNumber = "62508750",
                            PostCode = 2325,
                            StatusId = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c")
                        },
                        new
                        {
                            Id = new Guid("415957e0-a9a5-4ad0-b053-a09f4c2a65fd"),
                            Address = "Hammersborggata 2",
                            BusinessId = new Guid("e3ead016-1f61-4dc9-b0f1-1f4ee2f27c16"),
                            County = "Oslo",
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(9570),
                            CustomerNumber = 0,
                            Email = "contact@sparebank1.no",
                            IsDeleted = false,
                            IsPrivateCustomer = false,
                            Name = "SpareBank 1",
                            OrganizationNr = 947032579,
                            PhoneNumber = "91504800",
                            PostCode = 106,
                            StatusId = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleId");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccafb929-aa82-4981-96f9-53864b688c89"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(8400),
                            IsDeleted = false,
                            Name = "UserServices"
                        },
                        new
                        {
                            Id = new Guid("dd5a13da-11e4-4554-a697-76a4102fd72e"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(8400),
                            IsDeleted = false,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StatusId");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_StatusId");

                    b.ToTable("Status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("728df2fc-4cbc-4945-8deb-b4e500f1898c"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(8590),
                            IsDeleted = false,
                            Name = "Lead"
                        },
                        new
                        {
                            Id = new Guid("08bc99d4-87ac-4f56-89e9-af19ab20ab95"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(8590),
                            IsDeleted = false,
                            Name = "Tatt Kontakt"
                        },
                        new
                        {
                            Id = new Guid("2b8cc7ea-d47b-4d01-90d9-1581ce380422"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(8590),
                            IsDeleted = false,
                            Name = "I Prosess"
                        },
                        new
                        {
                            Id = new Guid("edd4e8aa-d3bd-40f1-8a97-8da40cef43bb"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(8590),
                            IsDeleted = false,
                            Name = "Kunde"
                        },
                        new
                        {
                            Id = new Guid("60e8fa5e-560d-41f7-b16c-593e5b0cfd3b"),
                            CreatedBy = new Guid("e3611b6c-0380-46bd-b07f-0a3b85a52464"),
                            CreatedOn = new DateTime(2024, 5, 24, 20, 29, 55, 350, DateTimeKind.Utc).AddTicks(8600),
                            IsDeleted = false,
                            Name = "Avslått"
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserServices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_UserId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserServices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.HasOne("Domain.Entities.Business", "Business")
                        .WithMany("Customers")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Status", "Status")
                        .WithMany("Customers")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Domain.Entities.UserServices", b =>
                {
                    b.HasOne("Domain.Entities.Business", "Business")
                        .WithMany("Users")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Business", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Status", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
